### PR TITLE
TASK: Update SPDX license identifier in composer manifest

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by mficzel** [comment]
Was this by intention? I suggest to bring this in line with the rest of the core. On the other hand i do not care that much if you think it should be like this feel free to merge.

**Comment by kdambekalns** [comment]
I have no clue if this was by intention. I thought you invented fusion-afx… ;)

**Comment by kdambekalns** [comment]
Changed it, this way it fits Neos better anyway.

**Comment by mficzel** [comment]
Yeah and i am sure i had no special intention other than using the same license as fusion.

**Pull request merged**
